# Generated by Django 3.2 on 2021-05-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_name', models.CharField(default='', max_length=128, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('mobile_phone', models.BigIntegerField(unique=True, verbose_name='手机号')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='住址')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '客户基础信息表',
                'verbose_name_plural': '客户基础信息表',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True, verbose_name='菜单名称')),
                ('en_name', models.CharField(default='', max_length=128, unique=True, verbose_name='英文名称')),
                ('url', models.CharField(default='', max_length=254, unique=True, verbose_name='菜单地址')),
                ('hierarchy', models.IntegerField(default=1, verbose_name='菜单层级')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父级菜单id')),
                ('have_child', models.BooleanField(default=0, verbose_name='是否含有子菜单')),
                ('icon', models.CharField(default='', max_length=128, verbose_name='菜单图标')),
                ('have_message_bubble', models.BooleanField(default=0, verbose_name='是否具有消息气泡')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '菜单列表',
                'verbose_name_plural': '菜单列表',
                'ordering': ['u_time'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=128, verbose_name='密码')),
                ('true_name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='邮箱')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('mobile_phone', models.BigIntegerField(unique=True, verbose_name='手机号')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '账户信息表',
                'verbose_name_plural': '账户信息表',
                'ordering': ['-c_time'],
            },
        ),
    ]
