# Generated by Django 3.2 on 2021-04-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=16, null=True)),
                ('true_name', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('sex', models.CharField(choices=[('1', '男'), ('2', '女')], default='男', max_length=10)),
                ('mobile_phone', models.IntegerField(blank=True, max_length=11, null=True, unique=True)),
            ],
        ),
    ]
