# Generated by Django 3.2.3 on 2021-06-05 14:15

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_name', models.CharField(default='', max_length=128, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('mobile_phone', models.BigIntegerField(unique=True, verbose_name='手机号')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='住址')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '客户基础信息表',
                'verbose_name_plural': '客户基础信息表',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True, verbose_name='菜单名称')),
                ('to_path', models.CharField(default='#', max_length=128, verbose_name='跳转地址')),
                ('hierarchy', models.IntegerField(default=1, verbose_name='菜单层级')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父级菜单id')),
                ('have_child', models.BooleanField(default=True, verbose_name='是否含有子菜单')),
                ('icon', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='菜单图标')),
                ('have_message_bubble', models.BooleanField(default=False, verbose_name='是否具有消息气泡')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '菜单列表',
                'verbose_name_plural': '菜单列表',
                'ordering': ['u_time'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='用户名')),
                ('password', models.CharField(max_length=150, verbose_name='密码')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='姓')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, error_messages={'required': '性别不能为空'}, verbose_name='性别')),
                ('mobile_phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='是否登录')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='是否激活')),
                ('birthday', models.DateField(default=django.utils.timezone.now, verbose_name='出生日期')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后一次登录时间')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '账户信息表',
                'verbose_name_plural': '账户信息表',
                'ordering': ['-c_time'],
            },
        ),
    ]
