# Generated by Django 3.2.3 on 2021-06-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house_helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='house_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('subhead', models.CharField(max_length=150, verbose_name='副标题')),
                ('totalPrices', models.CharField(max_length=150, verbose_name='总价')),
                ('unitPrice', models.CharField(max_length=150, verbose_name='单价')),
                ('acreage', models.CharField(max_length=150, verbose_name='面积')),
                ('houseDoorModel', models.CharField(max_length=150, verbose_name='房屋户型')),
                ('floor', models.CharField(max_length=150, verbose_name='所在楼层')),
                ('familyStructure', models.CharField(max_length=150, verbose_name='户型结构')),
                ('insideSpace', models.CharField(max_length=150, verbose_name='套内面积')),
                ('buildingTypes', models.CharField(max_length=150, verbose_name='建筑类型')),
                ('buildingStructure', models.CharField(max_length=150, verbose_name='建筑结构')),
                ('buildingHead', models.CharField(max_length=150, verbose_name='房屋朝向')),
                ('decorateSituation', models.CharField(max_length=150, verbose_name='装修情况')),
                ('ladderHouseholdProportion', models.CharField(max_length=150, verbose_name='梯户比例')),
                ('haveElevator', models.CharField(max_length=150, verbose_name='是否用电梯')),
                ('propertyType', models.CharField(max_length=150, verbose_name='产权类型')),
                ('usageOfHouse', models.CharField(max_length=150, verbose_name='房屋用途')),
                ('propertyOwnership', models.CharField(max_length=150, verbose_name='产权所属')),
                ('villageName', models.CharField(max_length=150, verbose_name='小区名称')),
                ('area', models.CharField(max_length=150, verbose_name='所在地区')),
                ('communityIsIntroduced', models.CharField(max_length=150, verbose_name='小区介绍')),
                ('surroundingFacility', models.CharField(max_length=150, verbose_name='周边配套')),
                ('transportation', models.CharField(max_length=150, verbose_name='交通出现')),
                ('coreSellingPoint', models.CharField(max_length=150, verbose_name='核心卖点')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '房源信息表',
                'verbose_name_plural': '房源信息表',
                'ordering': ['-u_time'],
            },
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='标签名称')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '标签列表',
                'verbose_name_plural': '标签列表',
                'ordering': ['-u_time'],
            },
        ),
        migrations.CreateModel(
            name='tag_rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=150, verbose_name='规则名称')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '标签规则表',
                'verbose_name_plural': '标签规则表',
                'ordering': ['-u_time'],
            },
        ),
        migrations.CreateModel(
            name='tag_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='标签类型')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '标签类型表',
                'verbose_name_plural': '标签类型表',
                'ordering': ['-u_time'],
            },
        ),
        migrations.CreateModel(
            name='tag_rule_relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
                ('rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_helper.tag_rule', verbose_name='规则id')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_helper.tag', verbose_name='标签id')),
            ],
            options={
                'verbose_name': '标签规则与标签关系表',
                'verbose_name_plural': '标签规则与标签关系表',
                'ordering': ['-u_time'],
            },
        ),
        migrations.CreateModel(
            name='tag_relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_helper.base_info')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_helper.tag', verbose_name='标签id')),
            ],
            options={
                'verbose_name': '客户与标签关系表',
                'verbose_name_plural': '客户与标签关系表',
                'ordering': ['-u_time'],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_helper.tag_type'),
        ),
        migrations.CreateModel(
            name='call_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '来电'), (2, '去电')], default=1, verbose_name='通话类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('call_duration', models.IntegerField(verbose_name='通话时长')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
                ('contacts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_helper.base_info', verbose_name='联系人id')),
            ],
            options={
                'verbose_name': '通话记录表',
                'verbose_name_plural': '通话记录表',
                'ordering': ['-c_time'],
            },
        ),
    ]
