# Generated by Django 3.2.3 on 2021-06-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_helper', '0002_auto_20210611_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='base_info',
            new_name='BaseInfo',
        ),
        migrations.RenameModel(
            old_name='call_log',
            new_name='CallLog',
        ),
        migrations.RenameModel(
            old_name='house_info',
            new_name='HouseInfo',
        ),
        migrations.RenameModel(
            old_name='tag_relation',
            new_name='TagRelation',
        ),
        migrations.RenameModel(
            old_name='tag_rule',
            new_name='TagRule',
        ),
        migrations.RenameModel(
            old_name='tag_rule_relation',
            new_name='TagRuleRelation',
        ),
        migrations.RenameModel(
            old_name='tag_type',
            new_name='TagType',
        ),
    ]
