# Generated by Django 3.2 on 2021-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_helper', '0002_auto_20210416_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='密码')),
                ('true_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('1', '男'), ('2', '女')], default='男', max_length=10, verbose_name='性别')),
                ('mobile_phone', models.IntegerField(blank=True, null=True, unique=True, verbose_name='手机号')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '账户信息表',
                'verbose_name_plural': '账户信息表',
                'ordering': ['-c_time'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
