# Generated by Django 3.2 on 2021-04-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_helper', '0003_auto_20210417_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='邮箱'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile_phone',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
    ]
