# Generated by Django 3.2 on 2021-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_helper', '0004_auto_20210420_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='菜单名称')),
                ('url', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='菜单地址')),
            ],
        ),
    ]
