# Generated by Django 3.2 on 2021-04-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_helper', '0005_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='hierarchy',
            field=models.IntegerField(blank=True, default=1, null=True, unique=True, verbose_name='菜单层级'),
        ),
    ]
