# Generated by Django 3.2 on 2021-04-20 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house_helper', '0006_menus_hierarchy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menus',
            options={'ordering': ['-c_time'], 'verbose_name': '菜单列表', 'verbose_name_plural': '菜单列表'},
        ),
        migrations.AddField(
            model_name='menus',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='最后更新时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menus',
            name='u_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
