# Generated by Django 3.2 on 2021-04-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_helper', '0007_auto_20210420_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='url',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='菜单地址'),
        ),
    ]
