# Generated by Django 3.2 on 2021-04-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_helper', '0010_alter_menus_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menus',
            options={'ordering': ['-u_time'], 'verbose_name': '菜单列表', 'verbose_name_plural': '菜单列表'},
        ),
    ]
